platform :ios, '6.1'

pod 'AFNetworking', '~> 2.0'
pod 'JSONKit', '~> 1.4'
pod 'SDWebImage', '~> 3.6'
pod 'ICViewPager', '~> 1.5'
pod 'MBProgressHUD', '~> 0.8'
pod 'FMDB', '~> 2.3'
pod 'KxMenu', '~> 1'
pod 'SSKeychain', '~> 1.2.2'
pod 'JSONModel', '~> 0.13.0'
pod 'SAMCategories', '~> 0.5.1'
pod 'ZXingObjC', '~> 3.0'
pod 'SGActionView'
pod 'TouchJSON','~> 1.1'
pod 'Reachability','~> 3.2'
pod 'Onboard'
pod 'JDStatusBarNotification'
